server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      schema-locations:
        - classpath:db/table.sql
      data-locations:
        - classpath:db/data.sql
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false
      default_batch_fetch_size: 100 # in query 자동 작성
  output:
    ansi:
      enabled: always
  security:
    user:
      name: ssar
      password: 1234
    oauth2:
      client:
        registration:
          naver:
            client-id: 모름
            client-secret: 모름
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보를 json으로 받는데, response라는 키 값으로 네이버가 리턴해준다

logging:
  level:
    '[shop.donutmarket.donut]': DEBUG # DEBUG 레벨부터 에러 확인할 수 있게 설정하기
    '[org.hibernate.orm.jdbc.bind]': TRACE # 콘솔 쿼리에 ? 에 주입된 값 보기

meta:
  name: ${HS512_SECRET} # _대신 .을 쓸 수도 있다.
